### ISSUE TITLE
MC4 is rebooting due to a lot of errors from Hubitat integration

### ISSUE THREAD

**Issue by glenn-turbodad** [jbasen/Crestron-Hubitat-Integration#11]
I have used your Hubitat integration with my personal Crestron MC4 processor, with good results.
I noticed my processor was rebooting several times during the day.
I started to investigate a little bit, and it seems to me there is a lot of errors from the Hubitat modules. It seems the devices can not communicate with my Hubitat, and they get an error back to the processor.

Any suggestions?

This has been in use for about 4-5 months with no errors until last week.

I am using your latest version of Crestron-Hubitat-Integration.
Crestron FW: 2.7000.00031

Hubitat Hub Information
Platform Version:
hub-2.3.1.135
Hardware Version:
Rev C-7

The errors are looking like this:

 at Crestron.SimplSharp.Net.Http.HttpClient.Dispatch (Crestron.SimplSharp.Net.Http.HttpClientRequest aRequest) [0x00180] in <23cedc07790c4a29b540b0a4716f8e52>:0 
  at Hubitat_Integration.Hubitat.Send_Device_Command (System.String Command_Type, System.String Command, System.String Value1, System.String Value2, System.String Value3, System.String Device_ID, System.Int16 Forced_Refresh) [0x004f3] in <393d042d20a24ede882f3a3319d8d494>:0 
url = http://192.168.1.38/apps/api/36/devices/3/refresh?access_token=XXXXX
Hubitat-Send_Device_Command - Error Sending Device Command: Crestron.SimplSharp.Net.Http.HttpException: HTTP/1.1 404 Not Found
Connection: close
Date: Wed, 27 Apr 2022 18:21:33 GMT
Content-Type: text/html

at Crestron.SimplSharp.Net.Http.HttpClient.Dispatch (Crestron.SimplSharp.Net.Http.HttpClientRequest aRequest) [0x00180] in <23cedc07790c4a29b540b0a4716f8e52>:0 
  at Hubitat_Integration.Hubitat.Send_Device_Command (System.String Command_Type, System.String Command, System.String Value1, System.String Value2, System.String Value3, System.String Device_ID, System.Int16 Forced_Refresh) [0x004f3] in <393d042d20a24ede882f3a3319d8d494>:0 
url = http://192.168.1.38/apps/api/36/devices/133/refresh?access_token=XXXXX
Hubitat-Send_Device_Command - Error Sending Device Command: Crestron.SimplSharp.Net.Http.HttpException: HTTP/1.1 404 Not Found
Connection: close
Date: Wed, 27 Apr 2022 18:23:23 GMT
Content-Type: text/html

 at Crestron.SimplSharp.Net.Http.HttpClien
  2. Error: SimplPlus[App01] # 2022-04-27 20:19:32 # t.Dispatch (Crestron.SimplSharp.Net.Http.HttpClientRequest aRequest) [0x00180] in <23cedc07790c4a29b540b0a4716f8e52>:0 
  at Hubitat_Integration.Hubitat.Send_Device_Command (System.String Command_Type, System.String Command, System.String Value1, System.S
  3. Error: SimplPlus[App01] # 2022-04-27 20:19:32 # tring Value2, System.String Value3, System.String Device_ID, System.Int16 Forced_Refresh) [0x004f3] in <393d042d20a24ede882f3a3319d8d494>:0 

  4. Error: SimplPlus[App01] # 2022-04-27 20:19:32 # url = http://192.168.1.38/apps/api/36/devices/133/refresh?access_token=XXXXX

  5. Error: SimplPlus[App01] # 2022-04-27 20:20:22 # Hubitat-Send_Device_Command - Error Sending Device Command: Crestron.SimplSharp.Net.Http.HttpException: HTTP/1.1 404 Not Found
Connection: close
Date: Wed, 27 Apr 2022 18:20:23 GMT
Content-Type: text/html

**Comment by jbasen** [comment]
Hi Glen.  I don't want be the one passing the buck but it appears that the issue is on the hubitat side of things.  The URL that the Crestron code is generating looks to be correctly formed yet the hubitat doesn't like it and is returning a 404 error.  A few things to look at:

1) Did something change the device ID's as they are defined in the maker API?  If the ID's, as they are defined in the maker api, don't match the device ID you've entered into the various SimplWindows hubitat modules as a parameter, you will get a 404 error.  In the above messages your device IDs are 3, 133, and 36.

2) Does the Maker API app ID match what you have defined in hubitat comm manager module?  Again, if this is wrong the hubitat will return a 404 error.  Currently it shows as being 36 in the error messages above.

One other note.  I removed the access token from your post as that shouldn't be shared publicly.

Hope this helps

**Comment by glenn-turbodad** [comment]
Hi.
It seems the problem is with the doorlock. It seems to loose connection with my Hubitat. 
I will reconnect, and it will work again.

Thanks for your help.

Regards
