### ISSUE TITLE
C# files

### ISSUE THREAD

**Issue by micdre** [jbasen/Crestron-Hubitat-Integration#19]
Is it possible to get the C# files for this project?
Kind regards, Michel

**Comment by jbasen** [comment]
As it says in the Readme, the full source code is provided to people who pay the $100 fee.  This is one of the few modules I've written that requests a payment due to the significant amount of work that has gone into it.  The payment is simply used to provide funding for purchasing other smart home devices that I will write drivers for. 

Instructions for making the payment through PayPal are included in the help for the comm manager module.

Thanks
