### ISSUE TITLE
Level FB Timing/Delay

### ISSUE THREAD

**Issue by ZippoD** [jbasen/Crestron-Hubitat-Integration#5]
Hi Again, 
Not exactly an issue (I can't find the discussion tab, may be it is disable on your channel) but room for improvement. I noticed a delay when processing the parsed FB data. It seems to be quite similar across multiple attempts so I wonder if you purposely delaying the process in S#. 

Here is a debug screenshot of dimmer level change. The highlighted area is where possibly we could minimize (it is ~1.4 seconds). Or are we hitting limitation of S#/3 series speed?
This is best case scenario. Sometimes the hub adds another 0.5-1sec to respond which probably we have no control of.
![image](https://user-images.githubusercontent.com/71191392/97094507-b8dcd700-1644-11eb-8f77-8de050834a85.png)

**Comment by jbasen** [comment]
There aren’t any delays built int the Crestron code. As soon as a feedback message is received by the S# http server it is passed along to SimplWindows through S+.  

I expect the delays you are seeing are simply due to the chain of messaging that has to take place. 

Crestron command to turn on a light -> http message to hubitat-> rf to switch/dimmer -> rf from switch/dimmer back to hubitat-> http message to Crestron processor with feedback -> processing/parsing of message on Crestron processor 

There is a lot going on to make this happen.

**Comment by ZippoD** [comment]
Perhaps you did not have a chance to look at my screenshot. I am not talking about RF or most of the reaction chain, just this:
http message to Crestron processor with feedback **-> processing/parsing of message on Crestron processor**
There is clearly a ~1.4 second delay when processing the FB data.
Please look at the screenshot and notice the time at the highlighted event (1.919s) and the one above(0.562s).

**Comment by jbasen** [comment]
Sorry, I now see what you are referring to though I don't have an explanation.  I'm using an event handler exactly the way a Crestron engineer taught me to.  I don't know why that would cause that long a delay to make it back from S# to S+.

I wish I had a better answer for you.
